name: Deploy Neighborly Trust to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Web App
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_SUPABASE_URL: "https://rcvxvnfejbwvokwzcuav.supabase.co"
          NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdnh2bmZlamJ3dm9rd3pjdWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MTY3MDIsImV4cCI6MjEwMTA5MjcwMn0.WPwp8CeGuP8AIPejbe1i-fwkEJ4HtE0Ime3WJWHOvJw"
          NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: "8830072583:AAEYhpGNTgD9AMR5hd5RC0eX3QlBi3is73c"
          NEXT_PUBLIC_COMMISSION_PERCENTAGE: "8"
          NEXT_PUBLIC_BASE_PATH: "neighbourly_trust2"
          NEXT_PUBLIC_METERED_DOMAIN: "neighborly-trust.metered.live"
          NEXT_PUBLIC_METERED_API_KEY: "g9svnC4ovDhTm62lwrPy7meTdKudH5FHQ1suxEDh0BFl8O3f"
        run: |
          npx next build --no-lint
          touch ./out/.nojekyll

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
